CREATE DATABASE QL_THITRACNGHIEM
GO
USE QL_THITRACNGHIEM
GO

create table MONHOC
(
	MAMONHOC CHAR(20),
	TENMONHOC NVARCHAR(100),
	TGTHI INT,
	CONSTRAINT PK_MAMH PRIMARY KEY(MAMONHOC)
)
go


create table DETHI
(
	MADT CHAR(20),
	constraint PK_DETHI primary key(MADT)
)
GO
ALTER TABLE DETHI
ADD MAMH CHAR(20)
GO
ALTER TABLE DETHI
ADD CONSTRAINT FK_DT_MH FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMONHOC)
GO


create table CAUHOI
(
	NOIDUNG nvarchar(100),
	DA1 NVARCHAR(100),
	DA2 NVARCHAR(100),
	DA3 NVARCHAR(100),
	DA4 NVARCHAR(100),
	DA NVARCHAR(100),
	DAPAN nvarchar(100) not null,
	MADT CHAR(20) not null,
	CONSTRAINT PK_ND PRIMARY KEY(noidung,MADT),
	CONSTRAINT FK_MAdethi_CAUHOI FOREIGN KEY(MADT) REFERENCES DETHI(MADT)
)
go

SELECT * FROM DSNOPBAI WHERE MADETHI = ''
-- thêm sau: câu hỏi của giáo viên nào ?
create table GIAOVIEN
(
	MAGV CHAR(20),
	TENGIAOVIEN NVARCHAR(100),
	GIOITINH NCHAR(3),
	NGAYSINH DATETIME,
	CONSTRAINT PK_MAGV PRIMARY KEY(MAGV)
)
go
create table THISINH
(
	MATS CHAR(20),
	TENTHISINH NVARCHAR(100),
	GIOITINH NCHAR(3),
	NGAYSINH DATETIME
	CONSTRAINT PK_MATS PRIMARY KEY(MATS)
)
go
create table TAIKHOAN_TS
(
	TENTK VARCHAR(30),
	MATKHAU VARCHAR(30),
	IDTAIKHOAN CHAR(20),
	QUYEN NVARCHAR(50) CHECK(QUYEN='TS'),
	CONSTRAINT PK_TENTK PRIMARY KEY(TENTK),
	CONSTRAINT FK_ID_TS FOREIGN KEY(IDTAIKHOAN) REFERENCES THISINH(MATS)
)
GO
create table TAIKHOAN_GV
(
	TENTK VARCHAR(30),
	MATKHAU VARCHAR(30),
	IDTAIKHOAN CHAR(20),
	QUYEN NVARCHAR(50) CHECK(QUYEN='GV'),
	CONSTRAINT PK_TENTK_GV PRIMARY KEY(TENTK),
	CONSTRAINT FK_ID_GV FOREIGN KEY(IDTAIKHOAN) REFERENCES GIAOVIEN(MAGV)
)
GO


create table PHIEUDIEM
(
	MAPD int identity(1,1),
	MONTHI nvarchar(50),
	MADT char(20) not null,
	TONGSOCAU int,
	SOCAUDUNG int,
	SOCAUSAI int,
	DIEMTONG float,
	MATS CHAR(20),
	MAGV CHAR(20),
	CONSTRAINT PK_MAPHIEUDIEM PRIMARY KEY(MAPD),
	constraint fk_matsPD foreign key(MATS) REFERENCES THISINH(MATS),
	constraint fk_gvPD foreign key(MAGV) REFERENCES GIAOVIEN(MAGV)
)
GO
ALTER TABLE PHIEUDIEM
ADD CONSTRAINT FK_DSNB_PD FOREIGN KEY(MADT) REFERENCES DETHI(MADT)
GO



--========TABLE DSNOPBAI============--
create table DSNOPBAI
(
	MATHISINH CHAR(20),
	TENMONHOC NVARCHAR(100),
	SOCAUDUNG INT,
	SOCAUSAI INT,
	MADETHI CHAR(20),
	CONSTRAINT PK_DSNB PRIMARY KEY(MATHISINH, MADETHI),
	CONSTRAINT FK_DSNB_TS FOREIGN KEY(MATHISINH) REFERENCES THISINH(MATS),
	CONSTRAINT FK_DSNB_DT FOREIGN KEY(MADETHI) REFERENCES DETHI(MADT)
)
go



insert into monhoc(MAMONHOC,TENMONHOC,TGTHI) values('CSDL',N'Cơ sở dữ liệu',60);
insert into monhoc(MAMONHOC,TENMONHOC,TGTHI) values('LTCB',N'Lập trình C',45);
insert into monhoc(MAMONHOC,TENMONHOC,TGTHI) values('LTNC',N'Lập trình C#',90);

insert into DETHI values('001');
insert into DETHI values('002');
insert into DETHI values('003');


SELECT * FROM CAUHOI